Refactor/ refactor the refactor until it's refactored
JakeBalakrishna/daily-diet pull request #12
Opened 2024-01-31 10:45 UTC by JakeBalakrishna

2024-01-31 14:24 UTC, mattwilson02 requested changes

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> +  content: {
this issue is being caused by one of the children styles being rendered within this view.

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> +    width: 260
why?

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
>    text: {
this text has a color you need to apply

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> +    fontSize: 12,
this text also has a color

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
>      borderEndWidth: 1,
this is very sketchy, instead use a separator type component

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> +    paddingHorizontal: 17
just use 16, this design is not very explicitly done but using odd numbers can be dodgy

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> +    alignSelf: "center"
this shouldnt be necessary if you correctly apply to the container

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> -      <View id={id} style={styles.container}>
NOTE: all these styles are very messy and i think its because you have tried to apply the same thing to each property individually, and this is actually what is causing your problem with the little icon not rendering on your screen.

Try to find all the common properties and enforce them on the container, then work inwards from there

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealItem/index.tsx
> +          <View style={styles.textView}>
All these view's wrapping just one component should not be needed if you build the container properly

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealList/index.tsx
> +    marginHorizontal: 24,
this shouldn't need to be applied again

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealList/index.tsx
> +    marginTop: 32
i see you are using margintop 32 for all the main elements of the screen. try using gap: 32 on the main container in the screen level, then if u need some extra margin just apply it here

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealList/index.tsx
>    text: {
text here should be a certain color

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealList/index.tsx
> +    <ScrollView
A section list is a scroll view, you should not need to wrap that in another scroll view

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/NewMeal/index.tsx
> +    marginHorizontal: 24
that shouldnt be necesary

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Meals/MealList/index.tsx
> +        SectionSeparatorComponent={Separator}
on your section list, when you scroll on section list, the header title will stay in position absolute, covering certain meal items, there is a prop to disable that.

https://reactnative.dev/docs/sectionlist

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +    marginTop: 20
why not just apply padding to the container

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +    marginBottom: 20
why not just apply padding to the container

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +    marginTop: 2,
use gap on the container

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +  mealPercentText: {
this text should be a specific color

2024-01-31 14:24 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +    ? require("../../../assets/openGreen.png")
instead of that you can use expo vector icons to find appropriate icons for that

2024-01-31 14:57 UTC, JakeBalakrishna commented on src/Screens/HomeScreen.tsx
> +    paddingHorizontal: 24,
guy in the course does that, thought it was strange but thought it must be correct if you sent it to me.

2024-01-31 14:58 UTC, JakeBalakrishna commented on src/components/NewMeal/index.tsx
> +    marginBottom: 16,
oops

2024-01-31 16:25 UTC, mattwilson02 commented on src/Screens/HomeScreen.tsx
> +    paddingHorizontal: 24,
No because in that context, there is a carousel, so wrapping in a container wouldnt work. But you can't apply one solution to all contexts

2024-02-01 10:34 UTC, mattwilson02 approved these changes

2024-02-01 10:41 UTC, merged