chore: percentage logic
JakeBalakrishna/daily-diet pull request #9
Opened 2024-01-26 14:36 UTC by JakeBalakrishna

2024-01-26 15:04 UTC, mattwilson02 requested changes

2024-01-26 15:04 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +  // meals in diet as a percentage
write a function called calculatePercentage, with two params, for the two numbers you want to compare, x100.toFixed(2)

2024-01-26 15:04 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +  if (percentageInValue < 50) {
this should not be necessary because you are getting the mealsOutOfDiet from the selector now

2024-01-26 15:04 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +    renderPercentage = (
this is like almost exactly the same Jsx, just return it once and make conditional variables for color and percentage

2024-01-26 15:04 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
> +      </View>
You are missing subtitles, this should display a dynamic "in your diet" or "out of your diet"

2024-01-26 15:04 UTC, mattwilson02 commented on src/components/Percentage/index.tsx
make a logic that uses your percentage function, and conditionally calculate with inDiet or outOfDiet if inDiet is less than out of diet

2024-01-26 15:21 UTC, RicardoBrito1938 commented
Also giving a had here

1) Calulate only the percentage
2) declare a boolean  = percentage > 50 // this returns a boolean true or false
3) on percentage render field do "percentage ?? 0"  // this is to prevent NaN error

2024-01-26 15:59 UTC, mattwilson02 commented
Whoops, ricardo is right, u dont need the !inDiet number at all, only total and inDiet

2024-01-29 09:44 UTC, mattwilson02 approved these changes

2024-01-29 09:45 UTC, merged